/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sergii' at '7/19/16 11:33 PM' with Gradle 2.14.1
 *
 * @author sergii, @date 7/19/16 11:33 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
